### ISSUE TITLE
Can you please tell me what kind of .gl file I need for simplestGraphRendering?

### ISSUE THREAD

**Issue by shujaatak** [fmi-alg/libdts2#6]
I am poking around OpenGL and I found https://github.com/dbahrdt/simplestGraphRendering, I soon noticed that I need some kind of a file with .gl extension but I am completely blank, I don't know what that file actually contains and from where I can get one. So I searched further and found your libdts2 repository which mention the same simplestGraphRendering project so I hope you may help me in this case.
Is this possible that I could get a sample .gl file from somewhere or would I need to generate it myself?
What keywords I would need to use to search a sample .gl file on google?

**Comment by dbahrdt** [comment]
The formats are "defined" in the following 3 Lines:
The simplest format (nodes, edges), in libdts2 this is the graph format "simplest":
https://github.com/invor/simplestGraphRendering/blob/df7657fcf9ca89d0b37f9e4360524284e271f299/src/simplestGraphRendering.cpp#L800

Complex format (nodes, edges, faces, color information), in libdts2 "simplest_andre":
https://github.com/invor/simplestGraphRendering/blob/df7657fcf9ca89d0b37f9e4360524284e271f299/src/simplestGraphRendering.cpp#L892

Collision sphere graph, create with fmi-alg/gbons2:
https://github.com/invor/simplestGraphRendering/blob/df7657fcf9ca89d0b37f9e4360524284e271f299/src/simplestGraphRendering.cpp#L951

If you have further questions regarding the usage of simplestGraphRendering or found a Bug, please report it at the appropriate place (invor/simplestGraphRendering).
Note that you should use the dev branch since the master branch is out-dated.
